create or replace force view qa_scheme_names_for_testing_v AS
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "QA_SCHEME_NAMES_FOR_TESTING_V" ("USERNAME") AS 
  select username
from all_users
where username not in ( -- ORACLE
                       'SYS'
                      ,'SYSAUX'
                      ,'ANONYMOUS'
                      ,'APPQOSSYS'
                      ,'AUDSYS'
                      ,'AURORA$JIS$UTILITY$'
                      ,'AURORA$ORB$UNAUTHENTICATED'
                      ,'AWR_STAGE'
                      ,'CSMIG'
                      ,'CTXSYS'
                      ,'DBSFWUSER'
                      ,'DBSNMP'
                      ,'DIP'
                      ,'DMSYS'
                      ,'DSSYS'
                      ,'DVF'
                      ,'DVSYS'
                      ,'EXDSYS'
                      ,'EXFSYS'
                      ,'GGSYS'
                      ,'GSMADMIN_INTERNAL'
                      ,'GSMCATUSER'
                      ,'GSMUSER'
                      ,'LBACSYS'
                      ,'MDDATA'
                      ,'MDSYS'
                      ,'MGMT_VIEW'
                      ,'MTSSYS'
                      ,'ODM_MTR'
                      ,'ODM'
                      ,'OJVMSYS'
                      ,'OLAPSYS'
                      ,'ORACLE_OCM'
                      ,'ORDDATA'
                      ,'ORDPLUGINS'
                      ,'ORDSYS'
                      ,'ORMTN_SCHEMA'
                      ,'OSE$HTTP$ADMIN'
                      ,'OUTLN'
                      ,'PDBADMIN'
                      ,'PERFSTAT'
                      ,'REMOTE_SCHEDULER_AGENT'
                      ,'SI_INFORMTN_SCHEMA'
                      ,'SPATIAL_CSW_ADMIN_USR'
                      ,'SPATIAL_CSW_ADMIN'
                      ,'SPATIAL_WFS_ADMIN_USR'
                      ,'SPATIAL_WFS_ADMIN'
                      ,'SYS'
                      ,'SYSBACKUP'
                      ,'SYSDG'
                      ,'SYSKM'
                      ,'SYSMAN'
                      ,'SYSRAC'
                      ,'SYSTEM'
                      ,'SYS$UMF'
                      ,'TRACESVR'
                      ,'TSMSYS'
                      ,'WKPROXY'
                      ,'WKSYS'
                      ,'WMSYS'
                      ,'XDB'
                      ,'XS$NULL'
                      ,'XTISYS'
                       -- APEX
                      ,'APEX_LISTENER'
                      ,'APEX_PUBLIC_USER'
                      ,'APEX_REST_PUBLIC_USER'
                      ,'FLOWS_FILES'
                       -- ORDS
                      ,'ORDS_METADATA'
                      ,'ORDS_PUBLIC_USER'
                       --Public
                      ,'PUBLIC')
    -- APEX owner
and not regexp_like(username, '^APEX_[0-9]{4}00$');
